/**
 * Writes vectors/link-v1.json — the lean-link/1 contract as test vectors.
 *
 * Every value here comes from src/, and `test/vectors.test.ts` regenerates it
 * and fails on any difference, so the file cannot drift from the code. The
 * encodings are also pinned in lean/SingularityLean/Wire.lean, and the MACs and
 * the AES-GCM envelope were cross-checked once against Python's hmac and
 * cryptography (the library lean-worker's own instructions use).
 *
 *   npm run vectors -w singularity-lean-agent
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { roomId, seal, taskKey } from '../src/relay.js';
import {
  type CallBody,
  type Certificate,
  LINK_VERSION,
  argvDigest,
  encodeArgv,
  encodeCallBody,
  encodeCertificate,
  macHex,
  sha256Hex,
} from '../src/wire.js';

export const CLIENT_KEY = '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff';
export const NODE_KEY = 'ffeeddccbbaa99887766554433221100ffeeddccbbaa99887766554433221100';

export function vectors() {
  const source = 'theorem t : 1 + 1 = 2 := rfl\n';
  const body: CallBody = {
    client: 'singularity',
    server: 'lean-worker',
    nonce: 7,
    job: { kind: 'proveGoal', module: 'RequestProject.Protocol.Server', decl: 'P2P.replay_rejected', sourceDigest: sha256Hex(source) },
    fuelBudget: 300,
  };
  const cert: Certificate = {
    server: 'lean-worker',
    client: 'singularity',
    nonce: 7,
    job: body.job,
    outcome: { kind: 'proved', axioms: ['propext'] },
    kernelChecked: true,
    fuelUsed: 300,
  };
  // Non-ASCII and the separator characters, so byte length (not character
  // count) and the lack of escaping are both exercised.
  const failed: Certificate = { ...cert, outcome: { kind: 'failed', reason: 'λ: a,b|c' }, kernelChecked: false };
  const argv = ['--check', 'é'];

  const salt = 'twin-proof-wave-vi-xii-2026-09-17-mike';
  const iv = Buffer.from('000102030405060708090a0b', 'hex');
  const plaintext = '{"compiled":true,"theorems_proved":1,"sorrys_remaining":0,"warnings":0,"files_changed":["Twin.lean"],"theorems_added":[],"total_theorems":1,"total_sorrys":0}';

  return {
    version: LINK_VERSION,
    note: 'Generated by scripts/write-vectors.ts. Do not edit; regenerate.',
    keys: { client: CLIENT_KEY, node: NODE_KEY },
    source: { text: source, digest: sha256Hex(source) },
    call: { body, encoding: encodeCallBody(body), mac: macHex(CLIENT_KEY, encodeCallBody(body)) },
    certificate: { cert, encoding: encodeCertificate(cert), mac: macHex(NODE_KEY, encodeCertificate(cert)) },
    failedCertificate: { cert: failed, encoding: encodeCertificate(failed), mac: macHex(NODE_KEY, encodeCertificate(failed)) },
    argv: { argv, encoding: encodeArgv(argv), digest: argvDigest(argv) },
    relay: {
      salt,
      task: 'agent-a-wave-vi',
      agent: 'agent-a',
      key: taskKey('agent-a-wave-vi', salt).toString('hex'),
      room: roomId(salt, 'agent-a'),
      plaintext,
      envelope: seal(plaintext, { task: 'agent-a-wave-vi', salt, agent: 'agent-a', ts: '2026-10-01T00:00:00Z', iv }),
    },
  };
}

const here = dirname(fileURLToPath(import.meta.url));
export const VECTORS_PATH = join(here, '..', 'vectors', 'link-v1.json');

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(VECTORS_PATH, JSON.stringify(vectors(), null, 2) + '\n');
  process.stdout.write(`wrote ${VECTORS_PATH}\n`);
}
