import type { ChainSpec } from './types.js';

const eth = { name: 'Ether', symbol: 'ETH', decimals: 18 };
const sepoliaEth = { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 };

/**
 * Curated registry. Public endpoints are deliberately keyless so the tool works
 * on first run; anything serious should override them via SINGULARITY_RPC_<ID>
 * or ~/.singularity/config.json.
 */
export const BUILTIN_CHAINS: ChainSpec[] = [
  // ---------------------------------------------------------------- EVM
  {
    id: 'ethereum',
    name: 'Ethereum',
    family: 'evm',
    chainId: 1,
    nativeCurrency: eth,
    rpc: ['https://eth.llamarpc.com', 'https://ethereum-rpc.publicnode.com', 'https://rpc.ankr.com/eth'],
    explorer: 'https://etherscan.io',
    aliases: ['eth', 'mainnet', 'l1'],
  },
  {
    id: 'base',
    name: 'Base',
    family: 'evm',
    chainId: 8453,
    nativeCurrency: eth,
    rpc: ['https://mainnet.base.org', 'https://base-rpc.publicnode.com'],
    explorer: 'https://basescan.org',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum One',
    family: 'evm',
    chainId: 42161,
    nativeCurrency: eth,
    rpc: ['https://arb1.arbitrum.io/rpc', 'https://arbitrum-one-rpc.publicnode.com'],
    explorer: 'https://arbiscan.io',
    aliases: ['arb', 'arbitrum-one'],
  },
  {
    id: 'optimism',
    name: 'OP Mainnet',
    family: 'evm',
    chainId: 10,
    nativeCurrency: eth,
    rpc: ['https://mainnet.optimism.io', 'https://optimism-rpc.publicnode.com'],
    explorer: 'https://optimistic.etherscan.io',
    aliases: ['op', 'oeth'],
  },
  {
    id: 'polygon',
    name: 'Polygon PoS',
    family: 'evm',
    chainId: 137,
    nativeCurrency: { name: 'Polygon Ecosystem Token', symbol: 'POL', decimals: 18 },
    rpc: ['https://polygon-rpc.com', 'https://polygon-bor-rpc.publicnode.com'],
    explorer: 'https://polygonscan.com',
    aliases: ['matic'],
  },
  {
    id: 'bsc',
    name: 'BNB Smart Chain',
    family: 'evm',
    chainId: 56,
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    rpc: ['https://bsc-dataseed.bnbchain.org', 'https://bsc-rpc.publicnode.com'],
    explorer: 'https://bscscan.com',
    aliases: ['bnb', 'binance'],
  },
  {
    id: 'avalanche',
    name: 'Avalanche C-Chain',
    family: 'evm',
    chainId: 43114,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    rpc: ['https://api.avax.network/ext/bc/C/rpc', 'https://avalanche-c-chain-rpc.publicnode.com'],
    explorer: 'https://snowtrace.io',
    aliases: ['avax'],
  },
  {
    id: 'gnosis',
    name: 'Gnosis Chain',
    family: 'evm',
    chainId: 100,
    nativeCurrency: { name: 'xDAI', symbol: 'XDAI', decimals: 18 },
    rpc: ['https://rpc.gnosischain.com', 'https://gnosis-rpc.publicnode.com'],
    explorer: 'https://gnosisscan.io',
    aliases: ['xdai'],
  },
  {
    id: 'scroll',
    name: 'Scroll',
    family: 'evm',
    chainId: 534352,
    nativeCurrency: eth,
    rpc: ['https://rpc.scroll.io'],
    explorer: 'https://scrollscan.com',
  },
  {
    id: 'linea',
    name: 'Linea',
    family: 'evm',
    chainId: 59144,
    nativeCurrency: eth,
    rpc: ['https://rpc.linea.build'],
    explorer: 'https://lineascan.build',
  },
  {
    id: 'zksync',
    name: 'ZKsync Era',
    family: 'evm',
    chainId: 324,
    nativeCurrency: eth,
    rpc: ['https://mainnet.era.zksync.io'],
    explorer: 'https://explorer.zksync.io',
    aliases: ['era', 'zksync-era'],
  },
  {
    id: 'sepolia',
    name: 'Sepolia',
    family: 'evm',
    chainId: 11155111,
    nativeCurrency: sepoliaEth,
    rpc: ['https://ethereum-sepolia-rpc.publicnode.com', 'https://rpc.sepolia.org'],
    explorer: 'https://sepolia.etherscan.io',
    testnet: true,
  },
  {
    id: 'base-sepolia',
    name: 'Base Sepolia',
    family: 'evm',
    chainId: 84532,
    nativeCurrency: sepoliaEth,
    rpc: ['https://sepolia.base.org'],
    explorer: 'https://sepolia.basescan.org',
    testnet: true,
  },

  // ---------------------------------------------------------------- SVM
  {
    id: 'solana',
    name: 'Solana',
    family: 'svm',
    nativeCurrency: { name: 'Solana', symbol: 'SOL', decimals: 9 },
    rpc: [
      'https://api.mainnet-beta.solana.com',
      'https://solana-rpc.publicnode.com',
      'https://solana.drpc.org',
    ],
    explorer: 'https://solscan.io',
    aliases: ['sol'],
  },
  {
    id: 'solana-devnet',
    name: 'Solana Devnet',
    family: 'svm',
    nativeCurrency: { name: 'Solana', symbol: 'SOL', decimals: 9 },
    rpc: ['https://api.devnet.solana.com'],
    explorer: 'https://solscan.io',
    testnet: true,
  },

  // --------------------------------------------------------------- UTXO
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    family: 'utxo',
    nativeCurrency: { name: 'Bitcoin', symbol: 'BTC', decimals: 8 },
    rpc: ['https://mempool.space/api', 'https://blockstream.info/api'],
    explorer: 'https://mempool.space',
    aliases: ['btc'],
  },
  {
    id: 'bitcoin-testnet',
    name: 'Bitcoin Testnet',
    family: 'utxo',
    nativeCurrency: { name: 'Test Bitcoin', symbol: 'tBTC', decimals: 8 },
    rpc: ['https://mempool.space/testnet/api', 'https://blockstream.info/testnet/api'],
    explorer: 'https://mempool.space/testnet',
    testnet: true,
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    family: 'utxo',
    nativeCurrency: { name: 'Litecoin', symbol: 'LTC', decimals: 8 },
    rpc: ['https://litecoinspace.org/api'],
    explorer: 'https://litecoinspace.org',
    aliases: ['ltc'],
  },

  // ------------------------------------------------------------- Cosmos
  {
    id: 'cosmoshub',
    name: 'Cosmos Hub',
    family: 'cosmos',
    chainId: 'cosmoshub-4',
    nativeCurrency: { name: 'Atom', symbol: 'ATOM', decimals: 6 },
    rpc: ['https://rest.cosmos.directory/cosmoshub'],
    explorer: 'https://www.mintscan.io/cosmos',
    bech32Prefix: 'cosmos',
    denom: 'uatom',
    aliases: ['cosmos', 'atom', 'gaia'],
  },
  {
    id: 'osmosis',
    name: 'Osmosis',
    family: 'cosmos',
    chainId: 'osmosis-1',
    nativeCurrency: { name: 'Osmosis', symbol: 'OSMO', decimals: 6 },
    rpc: ['https://rest.cosmos.directory/osmosis'],
    explorer: 'https://www.mintscan.io/osmosis',
    bech32Prefix: 'osmo',
    denom: 'uosmo',
    aliases: ['osmo'],
  },
  {
    id: 'celestia',
    name: 'Celestia',
    family: 'cosmos',
    chainId: 'celestia',
    nativeCurrency: { name: 'Celestia', symbol: 'TIA', decimals: 6 },
    rpc: ['https://rest.cosmos.directory/celestia'],
    explorer: 'https://www.mintscan.io/celestia',
    bech32Prefix: 'celestia',
    denom: 'utia',
    aliases: ['tia'],
  },
  {
    id: 'injective',
    name: 'Injective',
    family: 'cosmos',
    chainId: 'injective-1',
    nativeCurrency: { name: 'Injective', symbol: 'INJ', decimals: 18 },
    rpc: ['https://rest.cosmos.directory/injective'],
    explorer: 'https://www.mintscan.io/injective',
    bech32Prefix: 'inj',
    denom: 'inj',
    aliases: ['inj'],
  },
  {
    id: 'dydx',
    name: 'dYdX Chain',
    family: 'cosmos',
    chainId: 'dydx-mainnet-1',
    nativeCurrency: { name: 'dYdX', symbol: 'DYDX', decimals: 18 },
    rpc: ['https://rest.cosmos.directory/dydx'],
    explorer: 'https://www.mintscan.io/dydx',
    bech32Prefix: 'dydx',
    denom: 'adydx',
  },
];

/** Chains queried by default when a portfolio request names no chains. */
export const DEFAULT_PORTFOLIO_CHAINS = [
  'ethereum',
  'base',
  'arbitrum',
  'optimism',
  'polygon',
  'solana',
  'bitcoin',
  'cosmoshub',
];
